# Activity 1

In [22]:
# AND gate perceptron
import numpy as np
# Sigmoid
def sigmoid(z):
    return 1 / (1 + np.exp(-z))
# Optional: Binary cross-entropy
def binary_cross_entropy(y, y_pred):
    return -np.mean(y * np.log(y_pred + 1e-9) + 
                    (1 - y) * np.log(1 - y_pred + 1e-9))
# Perceptron class
class Perceptron:
    def __init__(self, input_size, learning_rate=0.1):
        self.W = np.random.randn(input_size, 1)
        self.b = 0
        self.lr = learning_rate
    def forward(self, X):
        return sigmoid(np.dot(X, self.W) + self.b)
    def train(self, X, y, epochs=2000):
        y = y.reshape(-1, 1)
        for _ in range(epochs):
            y_pred = self.forward(X)
            dW = np.dot(X.T, (y_pred - y)) / len(X)
            db = np.mean(y_pred - y)
            self.W -= self.lr * dW
            self.b -= self.lr * db
    def predict(self, X):
        return (self.forward(X) >= 0.5).astype(int)
# AND Gate
X_and = np.array([[0,0],[0,1],[1,0],[1,1]])
y_and = np.array([0,0,0,1])
model_and = Perceptron(2)
model_and.train(X_and, y_and)
print("AND Gate Output:")
print(model_and.predict(X_and).flatten())

AND Gate Output:
[0 0 0 1]


In [24]:
# OR gate perecptron
X_or = np.array([[0,0],[0,1],[1,0],[1,1]])
y_or = np.array([0,1,1,1])
model_or = Perceptron(2)
model_or.train(X_or, y_or)
print("OR Gate Output:")
print(model_or.predict(X_or).flatten())

OR Gate Output:
[0 1 1 1]


In [26]:
# Binary classification datset
X = np.array([[1,1],[1,2],[2,1],[2,2],
              [6,6],[7,6],[6,7],[7,7]])
y = np.array([0,0,0,0,1,1,1,1])
model = Perceptron(2)
model.train(X, y)
print("Binary Classification Output:")
print(model.predict(X).flatten())

Binary Classification Output:
[0 0 0 0 1 1 1 1]


# Activity 2

In [35]:
# Handwritten digit recognition (MNIST)
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical

# Load MNIST dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# Normalize inputs
X_train = X_train / 255.0
X_test = X_test / 255.0

# One-hot encode outputs
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

#  Build MLP
model = Sequential([
    Flatten(input_shape=(28,28)),  # Convert 2D images to 1D vector
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')  # 10 classes for digits 0-9
])

#  Compile Model
model.compile(
    optimizer='adam', 
    loss='categorical_crossentropy', 
    metrics=['accuracy']
)

#  Train Model
model.fit(X_train, y_train, epochs=5, batch_size=32, validation_split=0.1)

#  Evaluate on Test Set
loss, accuracy = model.evaluate(X_test, y_test)
print("MNIST Test Accuracy:", accuracy)


C:\Users\Admin\anaconda3\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/5
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9274 - loss: 0.2495 - val_accuracy: 0.9688 - val_loss: 0.1044
Epoch 2/5
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9674 - loss: 0.1059 - val_accuracy: 0.9755 - val_loss: 0.0832
Epoch 3/5
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9769 - loss: 0.0723 - val_accuracy: 0.9735 - val_loss: 0.0909
Epoch 4/5
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9819 - loss: 0.0551 - val_accuracy: 0.9768 - val_loss: 0.0794
Epoch 5/5
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9868 - loss: 0.0416 - val_accuracy: 0.9775 - val_loss: 0.0786
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9770 - loss: 0.0759
MNIST Test Accuracy: 0.9769999980926514


In [36]:
# Breast cancer classification
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Load dataset
data = load_breast_cancer()
X = data.data
y = data.target

#  Split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#  Standardize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#  Build MLP
model = Sequential([
    Dense(32, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')  # Binary classification
])

# Compile model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

#  Train model
model.fit(X_train, y_train, epochs=50, batch_size=16, validation_split=0.1)

#  Evaluate
loss, accuracy = model.evaluate(X_test, y_test)
print("Breast Cancer Test Accuracy:", accuracy)


Epoch 1/50


C:\Users\Admin\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


26/26 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - accuracy: 0.7531 - loss: 0.5355 - val_accuracy: 0.8478 - val_loss: 0.4202
Epoch 2/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9242 - loss: 0.3221 - val_accuracy: 0.9130 - val_loss: 0.2634
Epoch 3/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9462 - loss: 0.2101 - val_accuracy: 0.9130 - val_loss: 0.1877
Epoch 4/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9535 - loss: 0.1549 - val_accuracy: 0.9130 - val_loss: 0.1573
Epoch 5/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9584 - loss: 0.1257 - val_accuracy: 0.9130 - val_loss: 0.1395
Epoch 6/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9682 - loss: 0.1078 - val_accuracy: 0.9130 - val_loss: 0.1297
Epoch 7/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9707 - loss: 0.0954 - val_accuracy: 0.9130 - val_loss: 0.1223
Epoch 8/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9780 - loss: 0.0845 - val_accuracy: 0.9130 - val_loss: 0.1188
E

In [45]:
# Change number of layers
# Example: Add another hidden layer
model = Sequential([
    Flatten(input_shape=(28,28)),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),  # New layer
    Dense(10, activation='softmax')
])


In [49]:
# Change activation functions
Dense(64, activation='tanh')
Dense(32, activation='sigmoid')


<Dense name=dense_34, built=False>

In [51]:
# Change optimizer
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])
model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
